default: &default
  adapter: postgresql
  encoding: utf8
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: workstation

test:
  <<: *default
  database: test_workstation

production:
  <<: *default
  database: production_workstation
